# Example PyPI Publishing Caller Workflow
#
# This is a ready-to-use example for calling the reusable PyPI publishing workflow.
# Copy this to your repository at `.github/workflows/publish-pypi.yml`
#
# Repository-specific configuration:
# 1. Update `package-name` to match your PyPI package name
# 2. Update PyPI Trusted Publisher configuration (see migration guide)
# 3. Optionally adjust python-version, source-directory, etc.
#
# For image_detection repository, use:
#   package-name: 'image-preprocessing-detector'
#   source-directory: 'src'

name: Publish to PyPI

on:
  # Automatically publish when a release is created
  release:
    types: [published]

  # Allow manual triggering with TestPyPI option
  workflow_dispatch:
    inputs:
      use_testpypi:
        description: 'Publish to TestPyPI instead of PyPI'
        type: boolean
        required: false
        default: false

jobs:
  publish:
    uses: ByronWilliamsCPA/.github/.github/workflows/python-publish-pypi.yml@main
    with:
      # REQUIRED: Your PyPI package name (used in summary display)
      package-name: 'image-preprocessing-detector'  # ← UPDATE THIS

      # OPTIONAL: Publish to TestPyPI for testing (default: false)
      use-testpypi: ${{ inputs.use_testpypi || false }}

      # OPTIONAL: Python version for building (default: '3.12')
      python-version: '3.12'

      # OPTIONAL: Run security checks before publishing (default: true)
      # Runs Safety (dependency vulnerabilities) and Bandit (code security)
      run-security-checks: true

      # OPTIONAL: Source directory for security scans (default: 'src')
      source-directory: 'src'

    # REQUIRED: Permissions for OIDC Trusted Publishing
    permissions:
      id-token: write    # Required for PyPI OIDC authentication
      contents: read     # Required for checking out code artifacts

# PyPI Trusted Publisher Setup Instructions:
#
# 1. Go to https://pypi.org/manage/account/publishing/
# 2. Add GitHub Actions as Trusted Publisher:
#    - PyPI Project Name: image-preprocessing-detector
#    - Owner: ByronWilliamsCPA (or your GitHub username/org)
#    - Repository: image-preprocessing-detector (or your repo name)
#    - Workflow: publish-pypi.yml
#    - Environment: (leave blank)
#
# 3. For TestPyPI testing:
#    Go to https://test.pypi.org/manage/account/publishing/
#    Add same configuration as above
#
# 4. Test publishing:
#    gh workflow run publish-pypi.yml --field use_testpypi=true
#
# 5. Verify at:
#    https://test.pypi.org/project/image-preprocessing-detector/
#
# 6. Create release to publish to production PyPI:
#    git tag -a v1.0.0 -m "Release v1.0.0"
#    git push origin v1.0.0
#    gh release create v1.0.0 --generate-notes
